### ISSUE TITLE
Unknown parameter in input: "executionRoleArn"

### ISSUE THREAD

**Issue by sergio239new** [fabfuel/ecs-deploy#101]
Hi, i tried to deploy but got error:

Creating new task definition revision
Traceback (most recent call last):
  File "/usr/local/bin/ecs", line 11, in <module>
    sys.exit(ecs())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/ecs_deploy/cli.py", line 81, in deploy
    new_td = create_task_definition(deployment, td)
  File "/usr/local/lib/python2.7/site-packages/ecs_deploy/cli.py", line 291, in create_task_definition
    new_td = action.update_task_definition(task_definition)
  File "/usr/local/lib/python2.7/site-packages/ecs_deploy/ecs.py", line 545, in update_task_definition
    additional_properties=task_definition.additional_properties
  File "/usr/local/lib/python2.7/site-packages/ecs_deploy/ecs.py", line 65, in register_task_definition
    **additional_properties
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 575, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 630, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
**Unknown parameter in input: "executionRoleArn", must be one of: family, taskRoleArn, networkMode, containerDefinitions, volumes, placementConstraints**

any idea ?

**Comment by fabfuel** [comment]
Hi @sergio239new , please try to update your local version of `boto3`:
```bash
pip install boto3 --upgrade
```

Does this help?

Best
Fabian
