### ISSUE TITLE
error ecs deploy

### ISSUE THREAD

**Issue by wandelsonlb** [fabfuel/ecs-deploy#102]
ecs deploy CL-WebApp-Dev-azA-B SV-WEBAPP-DEV
Traceback (most recent call last):
  File "/usr/bin/ecs", line 11, in <module>
    load_entry_point('ecs-deploy==1.4.3', 'console_scripts', 'ecs')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ecs_deploy/cli.py", line 62, in deploy
    client = get_client(access_key_id, secret_access_key, region, profile)
  File "/usr/lib/python2.7/site-packages/ecs_deploy/cli.py", line 23, in get_client
    return EcsClient(access_key_id, secret_access_key, region, profile)
  File "/usr/lib/python2.7/site-packages/ecs_deploy/ecs.py", line 15, in __init__
    self.boto = session.client(u'ecs')
  File "/usr/lib/python2.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 889, in create_client
    client_config=config, api_version=api_version)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 76, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 291, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/lib/python2.7/site-packages/botocore/args.py", line 45, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/usr/lib/python2.7/site-packages/botocore/args.py", line 112, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 364, in resolve
    service_name, region_name)
  File "/usr/lib/python2.7/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/usr/lib/python2.7/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.

**Comment by fabfuel** [comment]
Dear @wandelsonlb,

unfortunately you did not provide any information or any context.
You just pasted a stack trace.

If you expect other people to spend **their time** to provide support for free, please spend **your time** first and provide context, information and yes, please read the error message you share. It contains all you need to fix your issue. I'm sure you'll figure it out.

If you still need support because you think there is an issue with this library, get back to us any time.

Best
Fabian
