### ISSUE TITLE
Botocore unknown parameter breaking ECS deploy

### ISSUE THREAD

**Issue by rosshettel** [fabfuel/ecs-deploy#166]
Running `ecs deploy` results in this error:

```$ ecs deploy services api --profile sandbox
Deploying based on task definition: api:17

Creating new task definition revision
Traceback (most recent call last):
  File "/usr/local/bin/ecs", line 8, in <module>
    sys.exit(ecs())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ecs_deploy/cli.py", line 95, in deploy
    new_td = create_task_definition(deployment, td)
  File "/usr/local/lib/python3.9/site-packages/ecs_deploy/cli.py", line 481, in create_task_definition
    new_td = action.update_task_definition(task_definition)
  File "/usr/local/lib/python3.9/site-packages/ecs_deploy/ecs.py", line 624, in update_task_definition
    response = self._client.register_task_definition(
  File "/usr/local/lib/python3.9/site-packages/ecs_deploy/ecs.py", line 80, in register_task_definition
    return self.boto.register_task_definition(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 648, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 696, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/usr/local/lib/python3.9/site-packages/botocore/validate.py", line 293, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "deregisteredAt", must be one of: family, taskRoleArn, executionRoleArn, networkMode, containerDefinitions, volumes, placementConstraints, requiresCompatibilities, cpu, memory, tags, pidMode, ipcMode, proxyConfiguration, inferenceAccelerators
```

Relevant versions:
- `ecs-deploy, version 1.11.2`
- `awscli          1.19.34`
- `boto3           1.17.34`
- `botocore        1.20.34`

Believe this is somewhat related to this issue: https://github.com/fabfuel/ecs-deploy/issues/154 just with a different field

**Comment by fabfuel** [comment]
Hi @rosshettel,

I have published a hotfix on PyPI, which fixes this issue:
https://pypi.org/project/ecs-deploy/1.11.3/

Best
Fabian

**Comment by rosshettel** [comment]
Wow, thank you for the quick reply!
