### ISSUE TITLE
syntax error v 1.12.0

### ISSUE THREAD

**Issue by AdamBogdan** [fabfuel/ecs-deploy#183]
Hey it seems that ecs deploy its not working anymore due to some syntax errors

Traceback (most recent call last):
  File "/opt/circleci/.pyenv/versions/2.7.12/bin/ecs", line 9, in <module>
    load_entry_point('ecs-deploy==1.12.0', 'console_scripts', 'ecs')()
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/ecs_deploy/cli.py", line 11, in <module>
    from ecs_deploy.ecs import DeployAction, ScaleAction, RunAction, EcsClient, DiffAction, \
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/ecs_deploy/ecs.py", line 9, in <module>
    from boto3.session import Session
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/botocore/session.py", line 30, in <module>
    import botocore.client
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/botocore/client.py", line 16, in <module>
    from botocore.args import ClientArgsCreator
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/botocore/args.py", line 26, in <module>
    from botocore.signers import RequestSigner
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/botocore/signers.py", line 19, in <module>
    import botocore.auth
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/botocore/auth.py", line 121
    pairs.append(f'{quoted_key}={quoted_value}')
                                              ^
SyntaxError: invalid syntax

Exited with code exit status 1

**Comment by AdamBogdan** [comment]
the command used is something like this -->  ecs deploy $ORG $SERVICE_NAME --tag $TAG --region <<parameters.REGION>> --ignore-warnings --timeout 1800

**Comment by AdamBogdan** [comment]
Hey Fabian , managed to update the python version to 3.7  . Now everything its working fine . Thank you for your help . 

Regards,

Bogdan
